### ISSUE TITLE
how to do l13 c1?

### ISSUE THREAD

**Issue by idkausernamewastaken** [paenis/csa-2022#1]

**Comment by paenis** [comment]
the captcha image is tied to the `seedID` used to request it:
![image](https://user-images.githubusercontent.com/46578974/164584957-bba1d252-5a66-474a-974d-89db69fd4405.png)

the same `seedID` is sent along with the rest of your input when you submit the form:
![image](https://user-images.githubusercontent.com/46578974/164585090-3dab6334-587b-43e0-b244-d983ff5fa70b.png)

you can bypass the captcha by just sending requests with the same `seedID` and `captcha` over and over, because the same seed will generate the same captcha

pretty sure this will work even if you use the same name/date for all requests; send about 5 requests and then reload for the flag

**Comment by paenis** [comment]
will add a readme and script eventually i just never got around to it

**Comment by idkausernamewastaken** [comment]
thanks man you saved me
